// Internationalization (i18n) handler for BG STICKERS website
// Handles language switching and updates all translatable elements

(function () {
  "use strict";

  // Update all elements with data-i18n attribute
  function updateAllTranslations() {
    const lang = getCurrentLanguage();
    document.documentElement.lang = lang;

    // Update all elements with data-i18n
    document.querySelectorAll("[data-i18n]").forEach(function (el) {
      const key = el.getAttribute("data-i18n");
      const translation = t(key);
      if (translation && translation !== key) {
        if (el.tagName === "INPUT" && el.type === "text" || el.tagName === "TEXTAREA") {
          // For inputs/textarea, update placeholder if data-placeholder exists
          const placeholderKey = el.getAttribute("data-placeholder");
          if (placeholderKey) {
            el.placeholder = t(placeholderKey);
          }
        } else if (el.tagName === "OPTION") {
          el.textContent = translation;
        } else if (el.tagName === "OPTGROUP") {
          const labelKey = el.getAttribute("data-i18n-label");
          if (labelKey) {
            el.label = t(labelKey);
          }
        } else {
          // Local trusted translations may include simple formatting tags such as <b>.
          el.innerHTML = translation;
        }
      }
    });

    // Update elements with data-placeholder (for inputs/textarea)
    document.querySelectorAll("[data-placeholder]").forEach(function (el) {
      const placeholderKey = el.getAttribute("data-placeholder");
      if (placeholderKey && (el.tagName === "INPUT" || el.tagName === "TEXTAREA")) {
        el.placeholder = t(placeholderKey);
      }
    });

    // Update language switcher active state
    document.querySelectorAll(".langBtn").forEach(function (btn) {
      const btnLang = btn.getAttribute("data-lang");
      if (btnLang === lang) {
        btn.classList.add("active");
      } else {
        btn.classList.remove("active");
      }
    });

    // Trigger custom event for other scripts to react
    window.dispatchEvent(new CustomEvent("languageChanged", { detail: { lang: lang } }));
    
    // Update dynamic content
    if (window.updateDynamicTranslations) {
      setTimeout(function() {
        window.updateDynamicTranslations();
      }, 50);
    }
  }

  // Initialize language switcher buttons
  function initLanguageSwitcher() {
    document.querySelectorAll(".langBtn").forEach(function (btn) {
      btn.addEventListener("click", function () {
        const lang = btn.getAttribute("data-lang");
        setCurrentLanguage(lang);
        updateAllTranslations();
        // Update dynamic content that might be generated by other scripts
        if (window.updateDynamicTranslations) {
          window.updateDynamicTranslations();
        }
      });
    });
  }

  // Initialize on DOM ready
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", function () {
      initLanguageSwitcher();
      updateAllTranslations();
    });
  } else {
    initLanguageSwitcher();
    updateAllTranslations();
  }

  // Expose update function globally for other scripts
  window.updateAllTranslations = updateAllTranslations;
})();
